#controllers:
#    resource: ../../src/Controller/
#    type: annotation

billing:
    resource: ../../src/Core/Billing/Presentation/Front/Controller
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
